# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svogrig <svogrig@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/22 03:03:35 by svogrig           #+#    #+#              #
#    Updated: 2025/03/09 18:17:01 by svogrig          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:=	materia

SRC 	:=	main.cpp \
			AMateria.cpp \
			MateriaSource.cpp \
			Cure.cpp \
			Ice.cpp \
			utils.cpp \
			Character.cpp

include ../ex00/Makefile
